@startuml
title RFC5545 Content Line parser.

' ---------------------------------------------------------------------------
' Content Line ABNF:
'   contentline   = name *(";" param ) ":" value CRLF
'
' <https://datatracker.ietf.org/doc/html/rfc5545#section-3.1>

[*] --> lookup_name

' ---------------------------------------------------------------------------
' name          = iana-token / x-name
' iana-token    = 1*(ALPHA / DIGIT / "-")
'   ; iCalendar identifier registered with IANA
'
' x-name        = "X-" [vendorid "-"] 1*(ALPHA / DIGIT / "-")
'   ; Reserved for experimental use.
' vendorid      = 3*(ALPHA / DIGIT)
'   ; Vendor identification

lookup_name: Skip empty space.
lookup_name --> [*]: char:eof-object?
lookup_name --> read_name: content-line:valid-name-character? -> push-event-to-buffer
lookup_name ->  lookup_name

read_name: Read content line name.
read_name --> [*]:             char:eof-object? -> content-line:error-param-eof
read_name --> read_param_name: char:semicolon? -> content-line:create
read_name --> read_value:      char:colon? -> content-line:create
read_name --> read_name:       content-line:valid-name-character? -> push-event-to-buffer
read_name --> [*]:             guard:#t -> content-line:error-invalid-name

' ---------------------------------------------------------------------------
' param         = param-name "=" param-value *("," param-value)
' param-name    = iana-token / x-name

read_param_name: Read parameter.
read_param_name --> [*]:              char:eof-object? -> content-line:error-param-eof
read_param_name --> read_param_value: char:equals-sign? -> content-line:store-param-name
read_param_name ->  read_param_name:  guard:#t -> push-event-to-buffer

' ---------------------------------------------------------------------------
' param-value   = paramtext / quoted-string
' paramtext     = *SAFE-CHAR
' quoted-string = DQUOTE *QSAFE-CHAR DQUOTE
' SAFE-CHAR     = WSP / %x21 / %x23-2B / %x2D-39 / %x3C-7E
'                   / NON-US-ASCII
' QSAFE-CHAR    = WSP / %x21 / %x23-7E / NON-US-ASCII
'   ; Any character except CONTROL and DQUOTE

read_param_value --> [*]:                      char:eof-object? -> content-line:error-param-eof
read_param_value --> read_param_value_quoted:  char:double-quote?
read_param_value --> read_param_name:          char:semicolon? -> content-line:store-param-value
read_param_value --> read_param_value_escaped: char:reverse-solidus?
read_param_value --> read_value:               char:colon? -> content-line:store-param-value
read_param_value --> read_param_value_list:    char:comma? -> content-line:store-param-value/list
read_param_value ->  read_param_value:         content-line:safe-char? -> push-event-to-buffer

read_param_value_escaped --> read_param_value: guard:#t -> content-line:store-escaped

read_param_value_quoted --> [*]:                     char:eof-object? -> content-line:error-param-eof
read_param_value_quoted --> read_param_value:        char:double-quote?
read_param_value_quoted --> read_param_value_quoted: content-line:qsafe-char? -> push-event-to-buffer
read_param_value_quoted --> [*]: guard:#t -> content-line:error-invalid-content-line

' ---------------------------------------------------------------------------
' List and Field Separators:
' <https://datatracker.ietf.org/doc/html/rfc5545#section-3.1.1>

read_param_value_list: Read and append parameter list value.
read_param_value_list --> [*]:                   char:eof-object? -> content-line:error-param-eof
read_param_value_list --> read_param_name:       char:semicolon? -> content-line:store-param-value/list
read_param_value_list --> read_value:            char:colon? -> content-line:store-param-value/list
read_param_value_list --> read_param_value_list: char:comma? -> content-line:store-param-value/list
read_param_value_list ->  read_param_value_list: content-line:safe-char? -> push-event-to-buffer

' ---------------------------------------------------------------------------
' VALUE-CHAR    = WSP / %x21-7E / NON-US-ASCII
'   ; Any textual characters
' NON-US-ASCII  = UTF8-2 / UTF8-3 / UTF8-4
'   ; UTF8-2, UTF8-3, and UTF8-4 are defined in [RFC3629]
'
' CONTROL       = %x00-08 / %x0A-1F / %x7F
'   ; All the controls except HTAB

read_value: Read content line value.
read_value --> [*]: char:eof-object? -> content-line:error-param-eof
read_value --> read_line_feed:     char:cr?
read_value --> read_value_escaped: char:reverse-solidus?
read_value --> read_value:         char:comma? -> content-line:store-value

' Some property values are defined in terms of multiple parts.  These
' structured property values MUST have their value parts separated by a
' SEMICOLON character.
'   <https://datatracker.ietf.org/doc/html/rfc5545#section-3.1.1>
read_value --> read_value:         char:semicolon? -> content-line:store-value

read_value ->  read_value:         content-line:value-char? -> push-event-to-buffer
read_value --> [*]:                guard:#t -> content-line:error-invalid-content-line

read_value_escaped --> read_value: guard:#t -> content-line:store-escaped

read_line_feed -> [*]: char:eof-object? -> content-line:error-param-eof
read_line_feed ->  check_for_multiline_text: char:lf?
read_line_feed --> [*]: guard:#t -> content-line:error-invalid-content-line

check_for_multiline_text -> [*]: char:eof-object? -> content-line:store-value
check_for_multiline_text -> read_value: char:space?
check_for_multiline_text -> [*]: guard:#t -> content-line:store-value/unget-char

@enduml

' Local Variables:
' Mode: plantuml
' End:
