@startuml
[*] --> lookup_object

lookup_object: Search the ICS object start.
lookup_object:
lookup_object: event-source: stream:read
lookup_object --> [*]:         stream:eof-object?
lookup_object --> read_object: stream:vcalendar-begin? -> stream:create-object
lookup_object --> lookup_object_error_corrupt_stream

lookup_object_error_corrupt_stream: The ICalendar stream has unexpected content.
lookup_object_error_corrupt_stream:
lookup_object_error_corrupt_stream: event-source: stream:dummy-event-source
lookup_object_error_corrupt_stream: exit-action:  stream:error
lookup_object_error_corrupt_stream --> [*]

read_object: Read an ICalendar object from the stream.
read_object: <https://datatracker.ietf.org/doc/html/rfc5545#section-3.4>
read_object:
read_object: event-source: stream:read
read_object --> read_object_error_eof:  stream:eof-object?
read_object --> lookup_object:          stream:vcalendar-end? -> stream:append-object
read_object --> read_vevent:            stream:vevent-begin? -> stream:create-component
read_object --> read_object:            guard:#t -> stream:append-property

read_object_error_eof: Unexpected EOF was read during VCALENDAR parsing.
read_object_error_eof:
read_object_error_eof: exit-action: stream:error-unexpected-eof-in-object
read_object_error_eof -> [*]

read_vevent: Read a VEVENT.
read_vevent:
read_vevent: event-source: stream:read
read_vevent --> read_vevent_error_eof:  stream:eof-object?
read_vevent --> read_object:            stream:vevent-end? -> stream:append-component
read_vevent --> read_vevent:            guard:#t -> stream:append-component-property

read_vevent_error_eof: Unexpected EOF was read during VEVENT parsing.
read_vevent_error_eof:
read_vevent_error_eof: event-source: stream:dummy-event-source
read_vevent_error_eof: exit-action:  stream:error-unexpected-eof-in-vevent
read_vevent_error_eof --> [*]

@enduml

' Local Variables:
' Mode: plantuml
' End:
