name: GNU Guile 3.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Required Packages
    strategy:
      matrix:
        distro:
          - 'ubuntu:20.04'
        include:
          - distro: 'ubuntu:20.04'
            pre: |
              apt --force-yes -qy install guile-3.0 guile-3.0-libs guile-3.0-dev guile-library texinfo gettext make automake autoconf
              && git clone https://github.com/artyom-poptsov/guile-smc
              && cd guile-smc
              && git checkout master
              && autoreconf -vif
              && ./configure --with-guilesitedir=/usr/share/guile/site/3.0 --prefix=/usr
              && sudo make -j$(nproc) install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test building on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          docker run --rm -e PRE -e DEBIAN_FRONTEND=noninteractive -v $PWD:/guile-ics -w /guile-ics ${{ matrix.distro }} /bin/sh -c '[ -n "${PRE}" ] && apt update && ${PRE} && autoreconf -vif && ./configure && make check'
